name: cert-manager-webhook-stackpath Docker Image CI

on:
  release:
    types: [published]

env:
  VERSION: 1.0.0

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ahhf/cert-manager-webhook-stackpath

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          tags: ahhf/cert-manager-webhook-stackpath:${{ env.VERSION }}
          build-args: version=${{ env.VERSION }}